### ISSUE TITLE
Real precision issue

### ISSUE THREAD

**Issue by petchema** [seism0saurus/hectoc#105]
Bot didn't accept my solution

98 + 8 ^ -2 * 2 ^ 7

for 988227, saying the result was 100.0000 and not 100.

**Comment by seism0saurus** [comment]
Thank you for the report.
I'm going to look into this today.

**Comment by seism0saurus** [comment]
I added a check to the result. If it is correct 100 without additional precision is returned. Otherwise the precision from the calculation is kept to prevent 100.00002 or or other near 100 results to be from beeing counted as correct.

This should fix the issue for the moment
