### ISSUE TITLE
Issue with ^?

### ISSUE THREAD

**Issue by petchema** [seism0saurus/hectoc#5]
Bot claimed that -46 + 12 ^ 2 + 2 = 112
Same with -46 + (12 ^ 2) + 2 = 112 so it doesn't seem to be a priority issue. I'm not sure how it comes up to that result

**Comment by seism0saurus** [comment]
Thank you for opening an issue.
I can confirm, that there is an error within the validation algorithm. I'm going to debug that and write a fix for the problem.
